# Generated by Django 5.1.5 on 2025-04-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
