# Generated by Django 5.1.5 on 2025-03-31 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant_product_color_varient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=100, unique=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
