# Generated by Django 5.1.5 on 2025-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
