# Generated by Django 5.1.5 on 2025-04-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_coupon_coupon_code_alter_coupon_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
